import { createHash } from "node:crypto";
import type { Observation } from "./types";
export type EntityCandidate={id:string;canonicalName:string;normalizedName:string;entityType:"organization"|"company"|"person"|"location"|"technology"|"product"|"vulnerability"|"industry"|"research_topic"|"economic_concept"|"event_type"|"unknown";mentionText:string;confidence:number};
const aliases:Record<string,{canonical:string;type:EntityCandidate["entityType"]}>={nasa:{canonical:"NASA",type:"organization"},usgs:{canonical:"USGS",type:"organization"},github:{canonical:"GitHub",type:"technology"},cisa:{canonical:"CISA",type:"organization"},"federal reserve":{canonical:"Federal Reserve",type:"organization"},"federal reserve board":{canonical:"Federal Reserve",type:"organization"},fed:{canonical:"Federal Reserve",type:"organization"},"national hurricane center":{canonical:"National Hurricane Center",type:"organization"},nhc:{canonical:"National Hurricane Center",type:"organization"},"national weather service":{canonical:"National Weather Service",type:"organization"},nws:{canonical:"National Weather Service",type:"organization"},"securities and exchange commission":{canonical:"SEC",type:"organization"},sec:{canonical:"SEC",type:"organization"},"department of justice":{canonical:"U.S. Department of Justice",type:"organization"},doj:{canonical:"U.S. Department of Justice",type:"organization"},openai:{canonical:"OpenAI",type:"company"},google:{canonical:"Google",type:"company"},apple:{canonical:"Apple",type:"company"},microsoft:{canonical:"Microsoft",type:"company"},cloudflare:{canonical:"Cloudflare",type:"company"},rubygems:{canonical:"RubyGems",type:"technology"},grapheneos:{canonical:"GrapheneOS",type:"technology"},"artificial intelligence":{canonical:"Artificial Intelligence",type:"technology"},ai:{canonical:"Artificial Intelligence",type:"technology"},"machine learning":{canonical:"Machine Learning",type:"technology"},cybersecurity:{canonical:"Cybersecurity",type:"industry"},semiconductor:{canonical:"Semiconductors",type:"industry"},semiconductors:{canonical:"Semiconductors",type:"industry"},inflation:{canonical:"Inflation",type:"economic_concept"},"interest rate":{canonical:"Interest Rates",type:"economic_concept"},"interest rates":{canonical:"Interest Rates",type:"economic_concept"},bitcoin:{canonical:"Bitcoin",type:"technology"},ethereum:{canonical:"Ethereum",type:"technology"},ransomware:{canonical:"Ransomware",type:"vulnerability"}};
const sourceEntities:Record<string,{canonical:string;type:EntityCandidate["entityType"]}>={"nasa-breaking":{canonical:"NASA",type:"organization"},"usgs-all-hour":{canonical:"USGS",type:"organization"},"github-blog":{canonical:"GitHub",type:"technology"},"cisa-news":{canonical:"CISA",type:"organization"},"fed-press":{canonical:"Federal Reserve",type:"organization"},"nhc-atlantic":{canonical:"National Hurricane Center",type:"organization"},"nhc-east-pacific":{canonical:"National Hurricane Center",type:"organization"},"nws-active-alerts":{canonical:"National Weather Service",type:"organization"},"sec-press":{canonical:"SEC",type:"organization"},"doj-news":{canonical:"U.S. Department of Justice",type:"organization"},"arxiv-ai":{canonical:"Artificial Intelligence",type:"research_topic"},"arxiv-crypto":{canonical:"Cryptography",type:"research_topic"},"hackernews-top":{canonical:"Hacker News",type:"technology"}};
function normalize(v:string){return v.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ")}
function identity(v:string){return normalize(v).replace(/\b(incorporated|inc|corporation|corp|limited|ltd|llc|plc|l p|lp)\b$/," ").replace(/\s+/g," ").trim()}
function makeCandidate(c:string,t:EntityCandidate["entityType"],m:string,q:number):EntityCandidate{const n=normalize(c),k=identity(c)||n;return{id:createHash("sha256").update(`entity\n${k}`).digest("hex").slice(0,24),canonicalName:c.replace(/\s+/g," ").trim(),normalizedName:n,entityType:t,mentionText:m,confidence:q}}
function add(f:Map<string,EntityCandidate>,c:string,t:EntityCandidate["entityType"],m:string,q:number){const clean=c.replace(/^[\s,:;–—-]+|[\s,:;.!?–—-]+$/g,"").trim();if(!clean||clean.length<2)return;const e=makeCandidate(clean,t,m.trim()||clean,q),old=f.get(e.id);if(!old||e.confidence>old.confidence)f.set(e.id,e)}
function structuredValue(s:string,k:string){const p=s.split(" | ").find(v=>v.startsWith(`${k}=`));return p?.slice(k.length+1).trim()}
const generic=new Set(["department of justice","federal reserve","securities and exchange commission","artificial intelligence","machine learning","hacker news","national weather service","national hurricane center","united states","press release","new study","board","agencies"]);
const badWords=/\b(highlights?|help|identify|enable|effective|modernize|rules?|meeting|readout|guidance|statement|data due|announcement|prescription|explorer|organizations?|threats?|risk)\b/i;
function plausibleName(v:string){const n=normalize(v);if(!n||generic.has(n)||badWords.test(v))return false;if(v.split(/\s+/).length>6)return false;return /[A-Z]/.test(v)&&!/^the\b/i.test(v)}
export function extractEntities(o:Observation):EntityCandidate[]{const f=new Map<string,EntityCandidate>(),raw=`${o.title} ${o.summary}`,text=normalize(raw),se=sourceEntities[o.sourceId];if(se)add(f,se.canonical,se.type,se.canonical,1);for(const[a,t]of Object.entries(aliases)){const n=normalize(a);if(new RegExp(`(^| )${n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}( |$)`).test(text))add(f,t.canonical,t.type,a,.99)}for(const cve of raw.match(/CVE-\d{4}-\d{4,7}/gi)??[])add(f,cve.toUpperCase(),"vulnerability",cve,1);for(const ticker of raw.match(/\b(?:NASDAQ|NYSE)\s*:\s*[A-Z]{1,5}\b/g)??[])add(f,ticker.toUpperCase(),"company",ticker,.99);for(const phrase of raw.match(/\b[A-Z][A-Za-z0-9&.'-]+(?:\s+[A-Z][A-Za-z0-9&.'-]+){0,5}\s+(?:Inc\.?|Corp\.?|Corporation|LLC|Ltd\.?|PLC|Bancorp|Bancshares|Holdings)\b/g)??[])add(f,phrase.replace(/[.,]$/,""),"company",phrase,.97);
 for(const m of o.title.matchAll(/\b([A-Z][A-Za-z0-9.+-]{2,}(?:\s+[A-Z][A-Za-z0-9.+-]{2,}){0,2})['’]s\b/g)){if(plausibleName(m[1]))add(f,m[1],"company",m[1],.92)}
 for(const token of o.title.match(/\b(?:OpenAI|RubyGems|GrapheneOS|Cloudflare|GitHub|Google|Apple|Microsoft|Amazon|Meta|Nvidia|NVIDIA)\b/g)??[])add(f,aliases[normalize(token)]?.canonical??token,aliases[normalize(token)]?.type??"company",token,.99);
 if(o.sourceId==="doj-news"){for(const m of raw.matchAll(/\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3}),?\s+(?:age\s+\d+|\d{2},|a\/k\/a|of\s+[A-Z])/g))add(f,m[1],"person",m[1],.94)}
 if(o.sourceId==="nws-active-alerts"){const event=structuredValue(o.summary,"event"),area=structuredValue(o.summary,"area"),sender=structuredValue(o.summary,"sender");if(event)add(f,event,"event_type",event,1);if(sender)add(f,sender,"organization",sender,1);if(area)for(const p of area.split(/;|,/).map(v=>v.trim()).filter(Boolean).slice(0,12))add(f,p,"location",p,.98)}return[...f.values()]}
