import type { HypothesisExpectation,HypothesisExpectationOutcome } from "./hypothesis-expectations";

function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("ARGUS persistent memory requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");return{url,key};}
async function request(path:string,method="GET",body?:unknown,prefer?:string){const{url,key}=config();const r=await fetch(`${url}/rest/v1/${path}`,{method,cache:"no-store",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})},body:body==null?undefined:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw new Error(`ARGUS expectation memory failed (${r.status}): ${text.slice(0,500)}`);return text.trim()?JSON.parse(text):null;}

export async function rememberExpectations(rows:HypothesisExpectation[]){if(!rows.length)return;await request("argus_hypothesis_expectations?on_conflict=id","POST",rows.map(e=>({id:e.id,hypothesis_id:e.hypothesisId,expectation_type:e.expectationType,statement:e.statement,created_at:e.createdAt,resolves_at:e.resolvesAt,status:e.status,expected_polarity:e.expectedPolarity,weight:e.weight,details:e.details})),"resolution=merge-duplicates,return=minimal");}
export async function rememberExpectationOutcomes(rows:HypothesisExpectationOutcome[]){if(!rows.length)return;await request("argus_hypothesis_expectation_outcomes?on_conflict=id","POST",rows.map(o=>({id:o.id,expectation_id:o.expectationId,resolved_at:o.resolvedAt,outcome:o.outcome,evidence_ids:o.evidenceIds,explanation:o.explanation,confidence_delta:o.confidenceDelta,model_version:o.modelVersion})),"resolution=ignore-duplicates,return=minimal");await Promise.all(rows.map(o=>request(`argus_hypothesis_expectations?id=eq.${encodeURIComponent(o.expectationId)}`,"PATCH",{status:"resolved"},"return=minimal")));}
export async function getExpectations(){const rows=(await request("argus_hypothesis_expectations?select=*&order=created_at.desc&limit=2000")??[]) as Array<Record<string,unknown>>;return rows.map(r=>({id:String(r.id),hypothesisId:String(r.hypothesis_id),expectationType:String(r.expectation_type) as HypothesisExpectation["expectationType"],statement:String(r.statement),createdAt:String(r.created_at),resolvesAt:String(r.resolves_at),status:String(r.status) as HypothesisExpectation["status"],expectedPolarity:String(r.expected_polarity) as HypothesisExpectation["expectedPolarity"],weight:Number(r.weight),details:r.details&&typeof r.details==="object"?r.details as Record<string,unknown>:{}}));}
export async function getExpectationOutcomes(){return (await request("argus_hypothesis_expectation_outcomes?select=*&order=resolved_at.desc&limit=2000")??[]) as Array<Record<string,unknown>>;}
