type Pattern={patternType:string;statement:string;scope:string;score:number;detectedAt:string};
type Hypothesis={hypothesisType:string;statement:string;confidence:number;rank:number;status:string;supportScore:number;contradictionScore:number};
type Expectation={statement:string;status:string;resolvesAt:string;weight:number;expectedPolarity:string};
type EventLink={linkType:string;confidence:number;observedAt:string};
export type IntelligenceBrief={generatedAt:string;headline:string;situation:string[];leadingExplanation?:string;alternativeExplanation?:string;watchNext:string[];temporalStructure:{total:number;overlaps:number;sequences:number;recurrences:number;highConfidence:number};epistemicNote:string};
export function buildIntelligenceBrief(input:{patterns:Pattern[];hypotheses:Hypothesis[];expectations:Expectation[];eventLinks:EventLink[];now?:string}):IntelligenceBrief{
 const now=input.now??new Date().toISOString();const active=input.hypotheses.filter(h=>h.status==="active").sort((a,b)=>b.confidence-a.confidence||a.rank-b.rank);const open=input.expectations.filter(e=>e.status==="open").sort((a,b)=>Date.parse(a.resolvesAt)-Date.parse(b.resolvesAt));const recent=[...input.patterns].sort((a,b)=>Date.parse(b.detectedAt)-Date.parse(a.detectedAt));
 const temporal={total:input.eventLinks.length,overlaps:input.eventLinks.filter(x=>x.linkType==="overlaps").length,sequences:input.eventLinks.filter(x=>x.linkType==="precedes").length,recurrences:input.eventLinks.filter(x=>x.linkType==="recurs_with").length,highConfidence:input.eventLinks.filter(x=>x.confidence>=.9).length};
 const situation=recent.slice(0,4).map(p=>p.statement);const lead=active[0],alt=lead?active.find(h=>h.hypothesisType!==lead.hypothesisType):active[1];
 const headline=recent.some(p=>p.patternType==="temporal_sequence_cluster")?"ARGUS is tracking a meaningful event sequence.":recent.some(p=>p.patternType==="regional_recurrence_cluster")?"ARGUS is tracking repeated activity in a shared region.":recent.some(p=>p.patternType==="cross_domain_convergence")?"Multiple observed domains are unusually active at the same time.":"ARGUS is observing the world model; no dominant higher-order structure is established.";
 return{generatedAt:now,headline,situation,leadingExplanation:lead?`${lead.statement} (${(lead.confidence*100).toFixed(1)}% current confidence)`:undefined,alternativeExplanation:alt?`${alt.statement} (${(alt.confidence*100).toFixed(1)}% current confidence)`:undefined,watchNext:open.slice(0,5).map(e=>`${e.statement} — due ${new Date(e.resolvesAt).toISOString()}`),temporalStructure:temporal,epistemicNote:"Patterns are detected structure; hypotheses are competing explanations; expectations and predictions are future claims. ARGUS does not present hypotheses as facts."};
}
