import { createHash } from "node:crypto";
import type { Observation } from "./types";
import type { EntityCandidate } from "./entities";
import type { ArgusEvent } from "./events";
export type TemporalRelationship={id:string;subjectEntityId:string;objectEntityId?:string;objectEventId?:string;relationshipType:"co_occurs_with"|"participates_in"|"issued"|"affected_by"|"classifies";validFrom:string;observedAt:string;confidence:number;derivationMethod:"deterministic_cooccurrence_v2"|"deterministic_entity_event_v3";evidenceObservationIds:string[]};
function eventRelation(entity:EntityCandidate,event:ArgusEvent):TemporalRelationship["relationshipType"]{if(entity.entityType==="location")return"affected_by";if(entity.entityType==="event_type")return"classifies";if(entity.entityType==="organization"&&entity.canonicalName===event.issuer)return"issued";return"participates_in";}
export function deriveRelationships(observation:Observation,entities:EntityCandidate[],events:ArgusEvent[]=[]):TemporalRelationship[]{const unique=[...new Map(entities.map(entity=>[entity.id,entity])).values()].sort((a,b)=>a.id.localeCompare(b.id));const relationships:TemporalRelationship[]=[];
 for(const event of events)for(const entity of unique){const relationshipType=eventRelation(entity,event);const id=createHash("sha256").update(`relationship\n${relationshipType}\n${entity.id}\n${event.id}`).digest("hex").slice(0,32);relationships.push({id,subjectEntityId:entity.id,objectEventId:event.id,relationshipType,validFrom:event.effectiveAt??observation.publishedAt,observedAt:observation.observedAt,confidence:entity.confidence,derivationMethod:"deterministic_entity_event_v3",evidenceObservationIds:[observation.id]});}
 const pairs=new Set<string>();for(let i=0;i<unique.length;i++)for(let j=i+1;j<unique.length;j++){const subject=unique[i],object=unique[j];if(subject.entityType==="location"&&object.entityType==="location")continue;const pairKey=`${subject.id}:${object.id}`;if(pairs.has(pairKey))continue;pairs.add(pairKey);const relationshipType="co_occurs_with" as const;const id=createHash("sha256").update(`relationship\n${relationshipType}\n${subject.id}\n${object.id}\n${observation.id}`).digest("hex").slice(0,32);relationships.push({id,subjectEntityId:subject.id,objectEntityId:object.id,relationshipType,validFrom:observation.publishedAt,observedAt:observation.observedAt,confidence:Math.min(subject.confidence,object.confidence),derivationMethod:"deterministic_cooccurrence_v2",evidenceObservationIds:[observation.id]});}return relationships;}
