import { createHash } from "node:crypto";
import type { Observation } from "./types";
import type { EntityCandidate } from "./entities";

export type SemanticDevelopment={id:string;entityId:string;entityName:string;entityType:string;detectedAt:string;domainCount:number;sourceCount:number;observationCount:number;novelty:number;specificity:number;consequenceScore:number;consequenceClass:string;targetDomains:string[];score:number;domains:string[];sourceIds:string[];statement:string;rationale:string;evidenceObservationIds:string[];modelVersion:"deterministic_semantic_convergence_v2"};
export const domainFor=(s:string)=>s.startsWith("nws-")||s.startsWith("nhc-")?"weather":s.startsWith("usgs-")?"geophysical":s.startsWith("cisa-")||s.startsWith("arxiv-crypto")?"cybersecurity":s.startsWith("fed-")?"monetary_policy":s.startsWith("sec-")?"markets_regulation":s.startsWith("doj-")||s.startsWith("whitehouse-")?"government_policy":s.startsWith("eia-")?"energy":s.startsWith("arxiv-ai")?"ai_research":s.startsWith("github-")||s.startsWith("hackernews-")?"technology":s.startsWith("nasa-")?"space_science":s.split("-")[0];
const specificityFor=(t:string,n:string)=>{const broad=new Set(["artificial intelligence","machine learning","cybersecurity","inflation","interest rates","cryptography"]);if(broad.has(n.toLowerCase()))return .2;return t==="vulnerability"?1:t==="company"||t==="product"?.95:t==="organization"?.78:t==="technology"?.62:t==="industry"||t==="economic_concept"||t==="research_topic"?.4:.3};
function consequence(domains:string[]){const s=new Set(domains);if(s.has("cybersecurity")&&s.has("technology"))return{c:"security_escalation",score:.95,target:["government_policy","markets_regulation","technology"]};if(s.has("markets_regulation")&&s.has("government_policy"))return{c:"regulatory_enforcement",score:.95,target:["markets_regulation","government_policy"]};if(s.has("monetary_policy")&&s.has("markets_regulation"))return{c:"institutional_market_response",score:.88,target:["markets_regulation","government_policy"]};if(s.has("ai_research")&&s.has("technology"))return{c:"technical_adoption",score:.78,target:["technology","markets_regulation"]};if(s.has("energy")&&s.has("government_policy"))return{c:"policy_infrastructure_response",score:.9,target:["energy","government_policy","markets_regulation"]};return{c:"cross_domain_follow_through",score:.55,target:domains};}
export function deriveSemanticDevelopments(entries:Array<{observation:Observation;entities:EntityCandidate[]}>,historical:Observation[]=[]):SemanticDevelopment[]{const by=new Map<string,{entity:EntityCandidate;rows:Observation[]}>();for(const entry of entries)for(const entity of entry.entities){if(entity.entityType==="event_type"||entity.entityType==="location"||entity.confidence<.82)continue;const row=by.get(entity.id)??{entity,rows:[]};row.rows.push(entry.observation);by.set(entity.id,row);}const currentIds=new Set(entries.map(e=>e.observation.id));const out:SemanticDevelopment[]=[];for(const {entity,rows} of by.values()){const sources=[...new Set(rows.map(r=>r.sourceId))],domains=[...new Set(sources.map(domainFor))].sort();if(sources.length<2||domains.length<2)continue;const prior=historical.filter(o=>!currentIds.has(o.id)&&`${o.title} ${o.summary}`.toLowerCase().includes(entity.canonicalName.toLowerCase())).length;const novelty=Number((1/(1+prior/4)).toFixed(4)),specificity=specificityFor(entity.entityType,entity.canonicalName),cons=consequence(domains);const raw=domains.length*1.8+sources.length*.9+Math.log2(rows.length+1)+novelty*3+specificity*4+cons.score*3;const score=Number((raw*specificity).toFixed(4));if(score<5.5)continue;const detectedAt=rows.map(r=>r.observedAt).sort().at(-1)!;const id=createHash("sha256").update(`semantic-development-v2\n${entity.id}\n${detectedAt.slice(0,13)}\n${cons.c}`).digest("hex").slice(0,32);const statement=`${entity.canonicalName}: unusual cross-domain activity spans ${domains.join(", ")}.`;const rationale=`Specificity ${(specificity*100).toFixed(0)}%; novelty ${(novelty*100).toFixed(0)}%; ${sources.length} independent sources; likely consequence class ${cons.c.replace(/_/g," ")}.`;out.push({id,entityId:entity.id,entityName:entity.canonicalName,entityType:entity.entityType,detectedAt,domainCount:domains.length,sourceCount:sources.length,observationCount:rows.length,novelty,specificity,consequenceScore:cons.score,consequenceClass:cons.c,targetDomains:cons.target,score,domains,sourceIds:sources.sort(),statement,rationale,evidenceObservationIds:[...new Set(rows.map(r=>r.id))].slice(0,100),modelVersion:"deterministic_semantic_convergence_v2"});}return out.sort((a,b)=>b.score-a.score).slice(0,20);}
