"use client";
import { useEffect, useMemo, useState } from "react";

type Observation={id:string;sourceId:string;title:string;publishedAt:string;url:string};
type Signal={id:string;kind:string;sourceId:string;score:number;observedAt:string;evidenceObservationIds:string[]};
type Inference={id:string;inferenceType:string;subjectScope:string;statement:string;confidence:number;inferredAt:string;evidenceObservationIds:string[]};
type Pattern={id:string;patternType:string;detectedAt:string;scope:string;score:number;statement:string;evidenceSignalIds:string[];evidenceObservationIds:string[]};
type Hypothesis={id:string;competitionGroup:string;hypothesisType:string;statement:string;generatedAt:string;confidence:number;rank:number;status:string;supportScore:number;contradictionScore:number;expectedEvidence:string[];falsifiers:string[]};
type HypothesisEvaluation={id:string;hypothesis_id?:string;hypothesisId?:string;evaluated_at?:string;evaluatedAt?:string;prior_confidence?:number;priorConfidence?:number;posterior_confidence?:number;posteriorConfidence?:number;support_delta?:number;supportDelta?:number;contradiction_delta?:number;contradictionDelta?:number;status:string;explanation:string};
type Expectation={id:string;hypothesisId:string;expectationType:string;statement:string;createdAt:string;resolvesAt:string;status:string;expectedPolarity:string;weight:number};
type ExpectationOutcome={id:string;expectation_id?:string;expectationId?:string;resolved_at?:string;resolvedAt?:string;outcome:boolean;explanation:string;confidence_delta?:number;confidenceDelta?:number};
type Prediction={id:string;statement:string;probability:number;status:string;resolvesAt:string;subjectScope:string};
type Outcome={id:string;predictionId:string;outcome:boolean;actualValue:number;targetValue:number;brierScore:number;resolvedAt:string};
type QueryResponse<T>={result:{classification:string;rows:T};llmProvider:string};
type Snapshot={observations:Observation[];signals:Signal[];inferences:Inference[];patterns:Pattern[];hypotheses:Hypothesis[];hypothesisEvaluations:HypothesisEvaluation[];expectations:Expectation[];expectationOutcomes:ExpectationOutcome[];predictions:Prediction[];outcomes:Outcome[]};
const empty:Snapshot={observations:[],signals:[],inferences:[],patterns:[],hypotheses:[],hypothesisEvaluations:[],expectations:[],expectationOutcomes:[],predictions:[],outcomes:[]};
const tabs=["overview","observations","signals","inferences","patterns","hypotheses","expectations","predictions","outcomes"] as const; type Tab=typeof tabs[number];
async function queryRows<T>(kind:string,limit=100):Promise<T[]>{const r=await fetch(`/api/query?kind=${kind}&limit=${limit}`,{cache:"no-store"});const b:QueryResponse<T[]>&{error?:string}=await r.json();if(!r.ok)throw new Error(b?.error??`Query failed: ${r.status}`);if(!b?.result||!Array.isArray(b.result.rows))throw new Error(`Invalid query payload for ${kind}`);return b.result.rows;}
function age(ts:string){const seconds=Math.max(0,Math.floor((Date.now()-new Date(ts).getTime())/1000));if(seconds<60)return`${seconds}s ago`;if(seconds<3600)return`${Math.floor(seconds/60)}m ago`;return`${Math.floor(seconds/3600)}h ago`;}
const num=(v:number|undefined)=>Number(v??0);

export default function Home(){
 const[data,setData]=useState<Snapshot>(empty);const[tab,setTab]=useState<Tab>("overview");const[loading,setLoading]=useState(true);const[observing,setObserving]=useState(false);const[error,setError]=useState<string|null>(null);
 async function refresh(){setLoading(true);setError(null);try{const[observations,signals,inferences,patterns,hypotheses,hypothesisEvaluations,expectations,expectationOutcomes,predictions,outcomes]=await Promise.all([queryRows<Observation>("observations"),queryRows<Signal>("signals"),queryRows<Inference>("inferences"),queryRows<Pattern>("patterns"),queryRows<Hypothesis>("hypotheses"),queryRows<HypothesisEvaluation>("hypothesis_evaluations"),queryRows<Expectation>("expectations"),queryRows<ExpectationOutcome>("expectation_outcomes"),queryRows<Prediction>("predictions"),queryRows<Outcome>("outcomes")]);setData({observations,signals,inferences,patterns,hypotheses,hypothesisEvaluations,expectations,expectationOutcomes,predictions,outcomes});}catch(e){setError(String(e));}finally{setLoading(false);}}
 async function observe(){setObserving(true);setError(null);try{const r=await fetch("/api/observe",{method:"POST"});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error??`Observe failed: ${r.status}`);if(Array.isArray(b?.errors)&&b.errors.length)setError(b.errors.join("\n"));await refresh();}catch(e){setError(String(e));}finally{setObserving(false);}}
 useEffect(()=>{void refresh();},[]);
 const openPredictions=useMemo(()=>data.predictions.filter(p=>p.status==="open"),[data.predictions]);const activeHypotheses=useMemo(()=>data.hypotheses.filter(h=>h.status==="active"),[data.hypotheses]);const openExpectations=useMemo(()=>data.expectations.filter(e=>e.status==="open"),[data.expectations]);const meanBrier=data.outcomes.length?data.outcomes.reduce((s,o)=>s+o.brierScore,0)/data.outcomes.length:null;
 return <main><header className="hero"><div><p className="eyebrow">AUTONOMOUS REASONING GRAPH FOR UNIFIED SIGNALS</p><h1>ARGUS</h1></div><div className="hero-side"><p className="status"><span/> ONLINE · LLM_PROVIDER=none</p><button onClick={observe} disabled={observing}>{observing?"OBSERVING…":"OBSERVE NOW"}</button></div></header>
 <nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t.toUpperCase()}</button>)}</nav>{error?<section className="error"><b>DIAGNOSTIC</b><pre>{error}</pre></section>:null}
 {tab==="overview"&&<><div className="grid six"><article><b>OBSERVATIONS</b><strong>{data.observations.length}</strong></article><article><b>PATTERNS</b><strong>{data.patterns.length}</strong></article><article><b>ACTIVE HYPOTHESES</b><strong>{activeHypotheses.length}</strong></article><article><b>OPEN EXPECTATIONS</b><strong>{openExpectations.length}</strong></article><article><b>OPEN PREDICTIONS</b><strong>{openPredictions.length}</strong></article><article><b>MEAN BRIER</b><strong>{meanBrier==null?"—":meanBrier.toFixed(3)}</strong></article></div>
 <section><h2>CURRENT INTELLIGENCE</h2>{activeHypotheses.length?<><p className="classification">HYPOTHESIS · RANK {activeHypotheses[0].rank} · {activeHypotheses[0].hypothesisType}</p><p className="lead">{activeHypotheses[0].statement}</p><p className="muted">Confidence {(activeHypotheses[0].confidence*100).toFixed(1)}% · support {activeHypotheses[0].supportScore.toFixed(2)} · contradiction {activeHypotheses[0].contradictionScore.toFixed(2)}</p></>:<p className="muted">No active hypothesis.</p>}</section>
 <div className="split"><section><h2>COMPETING EXPLANATIONS</h2>{activeHypotheses.slice(0,4).map(h=><div className="row" key={h.id}><span className="classification">HYPOTHESIS · #{h.rank}</span><p>{h.statement}</p><small>{(h.confidence*100).toFixed(1)}% · support {h.supportScore.toFixed(2)} · contradiction {h.contradictionScore.toFixed(2)}</small></div>)}</section><section><h2>WHAT ARGUS EXPECTS NEXT</h2>{openExpectations.slice(0,4).map(e=><div className="row" key={e.id}><span className="classification">EXPECTATION · {e.expectationType}</span><p>{e.statement}</p><small>{e.expectedPolarity.toUpperCase()} · weight {e.weight.toFixed(2)} · resolves {new Date(e.resolvesAt).toLocaleString()}</small></div>)}</section></div></>}
 {tab==="observations"&&<section><h2>LIVE OBSERVATION STREAM</h2>{data.observations.map(o=><div className="row" key={o.id}><span className="classification">OBSERVED FACT · {o.sourceId}</span><p><a href={o.url} target="_blank" rel="noreferrer">{o.title}</a></p><small>{new Date(o.publishedAt).toLocaleString()}</small></div>)}</section>}
 {tab==="signals"&&<section><h2>ANOMALY / SIGNAL QUEUE</h2>{data.signals.map(s=><div className="row" key={s.id}><span className="classification">SIGNAL · {s.kind}</span><p>{s.sourceId} · score {Number(s.score).toFixed(2)}</p><small>{s.evidenceObservationIds?.length??0} evidence observations · {age(s.observedAt)}</small></div>)}</section>}
 {tab==="inferences"&&<section><h2>INFERENCE LEDGER</h2>{data.inferences.map(i=><div className="row" key={i.id}><span className="classification">INFERENCE · {i.inferenceType}</span><p>{i.statement}</p><small>Confidence {(i.confidence*100).toFixed(1)}% · {i.evidenceObservationIds.length} evidence observations</small></div>)}</section>}
 {tab==="patterns"&&<section><h2>CROSS-DOMAIN PATTERNS</h2>{data.patterns.map(p=><div className="row" key={p.id}><span className="classification">PATTERN · {p.patternType}</span><p>{p.statement}</p><small>Scope {p.scope} · score {p.score.toFixed(2)} · {p.evidenceSignalIds.length} signals / {p.evidenceObservationIds.length} observations</small></div>)}</section>}
 {tab==="hypotheses"&&<section><h2>COMPETING HYPOTHESIS LEDGER</h2>{data.hypotheses.map(h=><div className="row" key={h.id}><span className="classification">HYPOTHESIS · {h.status.toUpperCase()} · RANK {h.rank}</span><p>{h.statement}</p><small>Confidence {(h.confidence*100).toFixed(1)}% · support {h.supportScore.toFixed(2)} · contradiction {h.contradictionScore.toFixed(2)}</small>{h.expectedEvidence?.length?<p className="muted">Expected next: {h.expectedEvidence[0]}</p>:null}{h.falsifiers?.length?<p className="muted">Would weaken it: {h.falsifiers[0]}</p>:null}</div>)}<h2>BELIEF REVISION HISTORY</h2>{data.hypothesisEvaluations.map((e,i)=><div className="row" key={e.id??i}><span className="classification">EVALUATION · {String(e.status).toUpperCase()}</span><p>{e.explanation}</p><small>{(num(e.priorConfidence??e.prior_confidence)*100).toFixed(1)}% → {(num(e.posteriorConfidence??e.posterior_confidence)*100).toFixed(1)}% · +{num(e.supportDelta??e.support_delta).toFixed(3)} support · -{num(e.contradictionDelta??e.contradiction_delta).toFixed(3)} contradiction</small></div>)}</section>}
 {tab==="expectations"&&<section><h2>HYPOTHESIS EXPECTATION LEDGER</h2>{data.expectations.map(e=><div className="row" key={e.id}><span className="classification">EXPECTATION · {e.status.toUpperCase()} · {e.expectationType}</span><p>{e.statement}</p><small>{e.expectedPolarity.toUpperCase()} · weight {e.weight.toFixed(2)} · deadline {new Date(e.resolvesAt).toLocaleString()}</small></div>)}<h2>RESOLVED EXPECTATIONS</h2>{data.expectationOutcomes.map((o,i)=><div className="row" key={o.id??i}><span className="classification">EXPECTATION OUTCOME · {o.outcome?"OBSERVED":"NOT OBSERVED"}</span><p>{o.explanation}</p><small>belief delta {num(o.confidenceDelta??o.confidence_delta)>=0?"+":""}{num(o.confidenceDelta??o.confidence_delta).toFixed(3)}</small></div>)}</section>}
 {tab==="predictions"&&<section><h2>PREDICTION LEDGER</h2>{data.predictions.map(p=><div className="row" key={p.id}><span className="classification">PREDICTION · {p.status}</span><p>{p.statement}</p><small>{(p.probability*100).toFixed(1)}% · resolves {new Date(p.resolvesAt).toLocaleString()}</small></div>)}</section>}
 {tab==="outcomes"&&<section><h2>OUTCOME / CALIBRATION LEDGER</h2>{data.outcomes.map(o=><div className="row" key={o.id}><span className="classification">OUTCOME · {o.outcome?"CONFIRMED":"MISSED"}</span><p>Actual {o.actualValue}; target {o.targetValue}</p><small>Brier {o.brierScore.toFixed(6)} · resolved {new Date(o.resolvedAt).toLocaleString()}</small></div>)}</section>}
 <footer><span>{loading?"QUERYING MEMORY…":"STRUCTURED QUERY ONLINE"}</span><span>OBSERVE → REMEMBER → MODEL → DETECT → CONNECT → INFER → HYPOTHESIZE → EXPECT → VERIFY → LEARN → PREDICT → EXPLAIN</span></footer></main>;
}
